"""
Django settings for mywebsite project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
import ssl, certifi
import logging
import pytz
from django.utils import timezone
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

logging.basicConfig(level=logging.DEBUG)

# Set the default timezone
timezone.activate(pytz.timezone('Asia/Jakarta'))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%8-jl3tb%8c4fjvp5g*)o@mj3ysm7!zh13p=14m3a-kl0fvrz&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [".taraalsyah.online",]

CSRF_TRUSTED_ORIGINS = [
    "https://taraalsyah.online",
    "https://www.taraalsyah.online",
    "https://about.taraalsyah.online",
    "https://www.about.taraalsyah.online",
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
AXES_PROXY_ORDER = "left-most"
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SAMESITE = "None"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'about',
    'crispy_forms',
    'crispy_bootstrap5',
    'ticket',
    
    # Required for allauth
    'django.contrib.sites',

    # allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    

    # Provider for Google
    'allauth.socialaccount.providers.google',
    
    # Django Extensions (baru ditambahkan)
    'django_extensions',
    'mywebsite',
    
    'axes',
    
]

SITE_ID = 4


MIDDLEWARE = [
    # Security headers & HTTPS handling
    'django.middleware.security.SecurityMiddleware',
    
    "whitenoise.middleware.WhiteNoiseMiddleware",

    # Session management (wajib sebelum AuthenticationMiddleware)
    'django.contrib.sessions.middleware.SessionMiddleware',

    # Common stuff (ETag, Content-Length, canonical redirects)
    'django.middleware.common.CommonMiddleware',

    # CSRF protection (harus sebelum AuthenticationMiddleware)
    'django.middleware.csrf.CsrfViewMiddleware',

    # User authentication (wajib sebelum middleware custom yang butuh request.user)
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    #for allauth
    'allauth.account.middleware.AccountMiddleware',
    
    # Middleware custom kamu
    'mywebsite.middleware.LoginRequiredMiddleware',
    'mywebsite.middleware.AutoLogoutMiddleware',

    # Messages framework
    'django.contrib.messages.middleware.MessageMiddleware',

    # Prevent clickjacking
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    #
    'axes.middleware.AxesMiddleware',
    
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    
]


ROOT_URLCONF = 'mywebsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                 os.path.join(BASE_DIR, 'templates'),
                 ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mywebsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'djangoproject',
        'USER': 'root',
        'PASSWORD' : 'Talsyah194598',
        'HOST' : 'localhost',
        'PORT' : '3307',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True

pytz.timezone('Asia/Jakarta')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static')
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirect here after successful login if no ?next= param
LOGIN_REDIRECT_URL = '/ticket/dashboard/'  # after login, go here

# Redirect to login page if user not authenticated or session timeout
LOGIN_URL = 'login'

LOGOUT_REDIRECT_URL = 'login' # after logout, go here


# Session will expire after 30 minutes of inactivity
SESSION_COOKIE_AGE = 30 * 60  # 30 minutes in seconds
SESSION_SAVE_EVERY_REQUEST = True  # Reset timer on each request
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Optional: end session when browser closes


#email config

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'taraalsyah45@gmail.com'
EMAIL_HOST_PASSWORD = 'qjbpveviahwrvgeo'  # Gunakan App Password jika 2FA aktif

EMAIL_SSL_CONTEXT = ssl.create_default_context(cafile=certifi.where())

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"



SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '589514036411-440sc20l44vcpkk11ffcjtahkli37rt1.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
            'prompt': 'select_account' # This forces Google to show the account chooser
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}

#LOGGING = {
#    'version': 1,
#    'disable_existing_loggers': False,
#    'handlers': {
#        'console': {
#            'class': 'logging.StreamHandler',
#        },
#    },
#    'loggers': {
#        'django': {
#            'handlers': ['console'],
#            'level': 'DEBUG',
#        },
#        'allauth': {
#            'handlers': ['console'],
#            'level': 'DEBUG',
#        },
#    },
#}


# Django-Allauth updated settings
ACCOUNT_LOGIN_METHODS = {"email"}  # Login using email only

ACCOUNT_SIGNUP_FIELDS = [
    "email*",      # Required email field
    "password1*",  # Required password
    "password2*"   # Required password confirmation
]

# Optional but recommended

ACCOUNT_EMAIL_SUBJECT_PREFIX = "[MyWebsite] "

#logging.basicConfig(
#    level=logging.DEBUG,
#    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
#)

AUTH_USER_MODEL = 'mywebsite.CustomUser'

# Disable automatic signup via Google
SOCIALACCOUNT_AUTO_SIGNUP = False # Disable automatic signup
 
# Require email confirmation before linking Google
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
#ACCOUNT_EMAIL_REQUIRED = True

ACCOUNT_SIGNUP_FIELDS = ['username*', 'email*', 'password1*', 'password2*']
SOCIALACCOUNT_STORE_TOKENS = True # Save Google tokens in the database
SOCIALACCOUNT_ADAPTER = 'mywebsite.adapters.CustomSocialAccountAdapter'

STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"

X_FRAME_OPTIONS = 'SAMEORIGIN'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AXES_FAILURE_LIMIT = 3
AXES_COOLOFF_TIME = timedelta(minutes=1)
AXES_LOCKOUT_PARAMETERS = [["ip_address", "username"]]