# Generated by Django 5.1.7 on 2025-03-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tara'),
    ]

    operations = [
        migrations.AddField(
            model_name='tara',
            name='email',
            field=models.EmailField(default='default@mail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='tara',
            name='judul',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
