# Generated by Django 5.1.7 on 2025-03-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Jurnal', 'Jurnal'), ('Berita', 'Berita'), ('Blog', 'Blog')], default='Select', max_length=20),
        ),
    ]
