# Generated by Django 5.1.7 on 2025-09-06 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_city_post_country_post_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='timezone',
            field=models.CharField(default='Asia/Jakarta', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
