# Generated by Django 5.1.7 on 2026-04-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0005_customer'),
    ]

    operations = [
    ]
