# Generated by Django 5.1.7 on 2025-03-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=10000)),
                ('handphone', models.IntegerField()),
                ('sex', models.CharField(choices=[('Man', 'Man'), ('Women', 'Women')], default='Select', max_length=5)),
            ],
        ),
    ]
