# Generated by Django 5.1.7 on 2025-03-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdb',
            name='handphone',
            field=models.BigIntegerField(),
        ),
    ]
