# Generated by Django 5.1.7 on 2025-08-23 12:05

import about.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutdb_handphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdb',
            name='handphone',
            field=models.BigIntegerField(validators=[about.validators.validate]),
        ),
    ]
