# Generated by Django 5.1.7 on 2025-12-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'In-Progress'), ('3', 'Closed')], default='1', max_length=20),
        ),
    ]
