# Generated by Django 5.1.7 on 2025-12-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attachments',
            field=models.FileField(null=True, upload_to='attachments/'),
        ),
    ]
