# Generated by Django 5.1.7 on 2025-12-28 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_alter_ticket_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_by', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='ticket_history/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(db_column='ticket_id', on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='ticket.ticket')),
            ],
            options={
                'db_table': 'ticket_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
