# Generated by Django 5.1.7 on 2025-12-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_alter_tickethistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickethistory',
            name='status',
            field=models.IntegerField(default=3),
        ),
    ]
