# Generated by Django 5.1.7 on 2025-12-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_alter_tickethistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickethistory',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'In-Progress'), (3, 'Closed')], default=3),
        ),
    ]
